#include "GameGlobal.h"

D3DCOLOR D3DCOLOR_BACKGROUND = BACKGROUND_COLOR;

std::unordered_map<int, bool> keyCode;
float globle_time;

 float ZONE_GHOST_1_LEFT;
 float ZONE_GHOST_1_RIGHT;
 float ZONE_GHOST_2_LEFT;
 float ZONE_GHOST_2_RIGHT;
 float ZONE_GHOST_3_LEFT;
 float ZONE_GHOST_3_RIGHT;
 float ZONE_PANTHER_1_LEFT;
 float ZONE_PANTHER_1_RIGHT;
 float ZONE_BAT_1_LEFT;
 float ZONE_BAT_1_RIGHT;

 float ZONE_FISHMAN_1_LEFT;
 float ZONE_FISHMAN_1_RIGHT;

 float ZONE_FISHMAN_2_LEFT;
 float ZONE_FISHMAN_2_RIGHT;
 float ZONE_FISHMAN_3_LEFT;
 float ZONE_FISHMAN_3_RIGHT;
 float ZONE_FISHMAN_4_LEFT;
 float ZONE_FISHMAN_4_RIGHT;

float ZONE_FULL_MAP_LEFT;
float ZONE_FULL_MAP_RIGHT;
float ZONE_STAGE1_LEFT;
float ZONE_STAGE1_RIGHT;
float ZONE_STAGE2_LEFT;
float ZONE_STAGE2_RIGHT;
float ZONE_STAGE3_LEFT;
float ZONE_STAGE3_RIGHT; 
float ZONE_BOSS_LEFT;
float ZONE_BOSS_RIGHT;

float GLOBAL_TIME;
float TIME_USE_HOLY_CROSS;
float UPGRADE_TIME;
float TIME_TO_RESPAWN;
float TIME_USE_STOP_WATCH;
float UNTOUCHABLETIME;
float TIMETOSPAWNCRYSTAL;

float CRYSTAL_SPAWN_X;
float CRYSTAL_SPAWN_Y;

float FISHMAN_POSY;
float FISHMAN1_POSX;
float FISHMAN2_POSX;
float FISHMAN3_POSX;
float FISHMAN4_POSX;
float FISHMAN5_POSX;
float FISHMAN6_POSX;
float FISHMAN7_POSX;
float FISHMAN8_POSX;


float GHOST_POSY;
float SPECIAL_GHOST_POSY;
float POSX_TOCREATESPECIALGHOST;

float BAT1_POSY;
float BAT2_POSY;
float BAT3_POSY;

float POSY_TOCREATEBAT;
float POSY_TONOTCREATEBAT;
float POSX_TONOTCREATEBAT;

float DISTANCE_TOACTIVE_PANTHER;

float POSX_ACTIVE_BOSS;